stages:
 - build
 #- push_to_ecr
 #- deploy

variables:
  # this variable can be overriden by pipeline run variable
  ENV: "sandbox"

.sandbox_triggers: &sandbox_triggers
  refs:
    - sandbox

.qat_triggers: &qat_triggers
  refs:
    - qat

.poc_triggers: &poc_triggers
  refs:
    - poc

build-sandbox:
  stage: build
  tags:
    - pass-sandbox
  script:
    - rm -rf tools
    - git clone http://$USER:$CI_TOKEN@gitlab.tooling-sapien.network/group-tools/tools.git
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-sandbox-cluster
    - export AWS_PROFILE=sapien-sandbox
    - export AWS_REGION=us-east-2
    - export ENV=SANDBOX
    - export NODE_ENV=SANDBOX
    - envsubst < .env.example > .env
    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 994750220687.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t passport:$CI_COMMIT_SHORT_SHA .
    - docker tag passport:$CI_COMMIT_SHORT_SHA 994750220687.dkr.ecr.us-east-2.amazonaws.com/passport:$CI_COMMIT_SHORT_SHA
    - docker push 994750220687.dkr.ecr.us-east-2.amazonaws.com/passport:$CI_COMMIT_SHORT_SHA
    - cd eks-manif &&  envsubst <  passport-dep-temp.yml > passport-dep.yml
    - cat passport-dep.yml
    - kubectl apply -f passport-dep.yml
  environment:
    name: sandbox
    url: https://passport-sandbox.sapien.network
  only:
    <<: *sandbox_triggers

build-qat:
  stage: build
  tags:
    - pass-qat
  script:
    - rm -rf tools
    - git clone http://$USER:$CI_TOKEN@gitlab.tooling-sapien.network/group-tools/tools.git
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-qat-cluster
    - export AWS_PROFILE=sapien-qat
    - export AWS_REGION=us-east-2
    - export ENV=QAT
    - export NODE_ENV=QAT
    - envsubst < .env.example > .env
    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 081984521558.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t passport:$CI_COMMIT_SHORT_SHA .
    - docker tag passport:$CI_COMMIT_SHORT_SHA 081984521558.dkr.ecr.us-east-2.amazonaws.com/passport:$CI_COMMIT_SHORT_SHA
    - docker push 081984521558.dkr.ecr.us-east-2.amazonaws.com/passport:$CI_COMMIT_SHORT_SHA
    - cd eks-manif &&  envsubst <  passport-dep-temp-qa.yml  > passport-dep.yml
    - cat passport-dep.yml
    - kubectl apply -f passport-dep.yml
  environment:
    name: qat
    url: https://passport-qat.sapien.network
  only:
    <<: *qat_triggers

build-poc:
  stage: build
  tags:
    - pass-poc
  script:
    - rm -rf tools
    - git clone http://$USER:$CI_TOKEN@gitlab.tooling-sapien.network/group-tools/tools.git
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-poc-cluster
    - export AWS_PROFILE=sapien-poc
    - export AWS_REGION=us-east-2
    - export ENV=POC
    - export NODE_ENV=POC
    - envsubst < .env.example > .env
    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 081984521558.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t passport:$CI_COMMIT_SHORT_SHA .
    - docker tag passport:$CI_COMMIT_SHORT_SHA 081984521558.dkr.ecr.us-east-2.amazonaws.com/passport:$CI_COMMIT_SHORT_SHA
    - docker push 081984521558.dkr.ecr.us-east-2.amazonaws.com/passport:$CI_COMMIT_SHORT_SHA
    - cd eks-manif &&  envsubst <  passport-dep-temp-prd.yml > passport-dep.yml
    - cat passport-dep.yml
    - kubectl apply -f passport-dep.yml
  environment:
    name: poc
    url: https://www.sapien.network
  only:
    <<: *poc_triggers
